spring:
log4j:
  logger:
    httpclient:
      wire: DEBUG

client:
  id: v9jpk-nCoD7ZTnC5Q4J6Tz5rOFYDRsKBACTzBXYSmj0=
  secret: qZ_8W9nULwjyIqYe_Yo_r-LENBH4zKKmFP8Tf255fns=
  redirectUri: http://localhost:4001/redirecting
  financialId: 0015800000jfwB4AAI
  state: ABC
  authorizationUsername: 123456789012@team.acc.org
  authorizationAccount: 50000012345601
  tokenUrl: https://ob.rbs.useinfinite.io/token
  initRunning: true


tls:
  alias:
  enableMatls: false
  keyStore:
    location:
    password:
  trustStore:
    location:
    password:

aisp:
  target:
    context: /open-banking/v3.1/aisp
    baseUri: https://ob.rbs.useinfinite.io
    audience: https://api.rbs.useinfinite.io/authorize

pisp:
  target:
    context: /open-banking/v3.1/pisp
    baseUri: https://ob.rbs.useinfinite.io
    audience: https://api.rbs.useinfinite.io/authorize